# Generated by Django 3.1.4 on 2021-01-03 10:35

import Doubts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('answer_text', models.CharField(max_length=500)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to=Doubts.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('question_text', models.CharField(max_length=500)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=Doubts.models.upload_image)),
                ('ans_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
