# Generated by Django 3.1.4 on 2021-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
