# Generated by Django 3.1.4 on 2021-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0003_auto_20210103_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
