# Generated by Django 3.1.4 on 2021-01-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0004_auto_20210103_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_dept',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('maths', 'Maths')], default='physics', max_length=20, null=True),
        ),
    ]
