# Generated by Django 3.1.4 on 2021-01-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0005_auto_20210103_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('maths', 'Maths')], default='physics', max_length=20, null=True),
        ),
    ]
