# Generated by Django 3.1.4 on 2021-01-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0006_auto_20210103_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
