# Generated by Django 3.1.4 on 2021-01-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0008_auto_20210103_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(null=True, upload_to='questions/'),
        ),
    ]
