# Generated by Django 3.1.4 on 2021-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0009_auto_20210103_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
