# Generated by Django 3.1.4 on 2021-01-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0011_auto_20210104_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(upload_to='questions/'),
        ),
    ]
