# Generated by Django 3.1.4 on 2021-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0012_auto_20210104_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ans_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
