# Generated by Django 3.1.4 on 2021-01-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0014_auto_20210104_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned',
            field=models.CharField(default=',', max_length=500, null=True),
        ),
    ]
