# Generated by Django 3.1.4 on 2021-01-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0015_auto_20210104_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_answer',
            fields=[
                ('answer_id', models.CharField(max_length=20, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('comment_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_question',
            fields=[
                ('question_id', models.CharField(max_length=20, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('comment_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='comments',
            field=models.TextField(default=',', max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='comments',
            field=models.TextField(default=',', max_length=100000, null=True),
        ),
    ]
