# Generated by Django 3.1.4 on 2021-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0016_auto_20210104_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_answer',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment_question',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
