# Generated by Django 3.1.4 on 2021-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0017_auto_20210105_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(null=True, upload_to='student_profile/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(null=True, upload_to='teacher_profile/'),
        ),
    ]
