# Generated by Django 3.1.4 on 2021-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0018_auto_20210106_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile/'),
        ),
    ]
