# Generated by Django 3.1.4 on 2021-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0019_auto_20210106_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profile/'),
        ),
    ]
