# Generated by Django 3.1.4 on 2021-01-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0020_auto_20210106_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='profile',
            new_name='image',
        ),
    ]
