# Generated by Django 3.1.4 on 2021-01-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0021_auto_20210106_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment_answer',
        ),
        migrations.DeleteModel(
            name='Comment_question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comments',
        ),
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
