# Generated by Django 3.1.4 on 2021-01-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0022_auto_20210106_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_dept',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], default='physics', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='student_profile/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], default='physics', max_length=20, null=True),
        ),
    ]
