# Generated by Django 3.1.4 on 2021-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0024_auto_20210106_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='teacher_profile/'),
        ),
    ]
