# Generated by Django 3.1.4 on 2021-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0025_auto_20210107_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, default='white.jpg', max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='white.jpg', upload_to='questions/'),
        ),
    ]
