# Generated by Django 3.1.4 on 2021-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0026_auto_20210107_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='white.jpg', null=True, upload_to='questions/'),
        ),
    ]
