# Generated by Django 3.1.4 on 2021-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0027_auto_20210107_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, default='white.jpg', null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
