# Generated by Django 3.1.4 on 2021-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0030_auto_20210108_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='white.jpg', upload_to='questions/'),
        ),
    ]
