# Generated by Django 3.1.4 on 2021-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0031_auto_20210108_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='profile.png', upload_to='questions/'),
        ),
    ]
