# Generated by Django 3.1.4 on 2021-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0032_auto_20210108_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='white.jpg', upload_to='questions/'),
        ),
    ]
