# Generated by Django 3.1.4 on 2021-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0032_auto_20210108_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='usernam',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, default='white.jpg', upload_to='questions/'),
        ),
    ]
