# Generated by Django 3.1.4 on 2021-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doubts', '0033_auto_20210108_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='usernam',
        ),
        migrations.AlterModelTable(
            name='answer',
            table='Doubts_Answer',
        ),
        migrations.AlterModelTable(
            name='get_info',
            table='Doubts_get_info',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Doubts_Question',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Doubts_Student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Doubts_Teacher',
        ),
    ]
